name: PerturbPred
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11.5
  - pytorch=2.0.1
  - cudatoolkit=11.8.0
  - scanpy=1.9.5
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - pandas=1.5.3